import 'package:the_crew_companion/entities/aimOption.dart';
import 'package:the_crew_companion/entities/mission.dart';

class MissionService {
  List<Mission> getMissions() {
    return [
      Mission(
        id: 0,
        aimCount: 1,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 1,
        aimCount: 2,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 2,
        aimCount: 2,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Two],
      ),
      Mission(
        id: 3,
        aimCount: 3,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 4,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 5,
        aimCount: 3,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.First, AimOption.Second, AimOption.Comms],
      ),
      Mission(
        id: 6,
        aimCount: 3,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Last],
      ),
      Mission(
        id: 7,
        aimCount: 3,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Two, AimOption.Three],
      ),
      Mission(
        id: 8,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 9,
        aimCount: 4,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 10,
        aimCount: 4,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Comms],
      ),
      Mission(
        id: 11,
        aimCount: 4,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Last],
      ),
      Mission(
        id: 12,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 13,
        aimCount: 4,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [
          AimOption.First,
          AimOption.Second,
          AimOption.Third,
          AimOption.Comms
        ],
      ),
      Mission(
        id: 14,
        aimCount: 4,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [
          AimOption.One,
          AimOption.Two,
          AimOption.Three,
          AimOption.Four
        ],
      ),
      Mission(
        id: 15,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 16,
        aimCount: 2,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 17,
        aimCount: 5,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Comms],
      ),
      Mission(
        id: 18,
        aimCount: 5,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Comms],
      ),
      Mission(
        id: 19,
        aimCount: 2,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Hidden],
      ),
      Mission(
        id: 20,
        aimCount: 5,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Two, AimOption.Comms],
      ),
      Mission(
        id: 21,
        aimCount: 5,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [
          AimOption.First,
          AimOption.Second,
          AimOption.Third,
          AimOption.Fourth
        ],
      ),
      Mission(
        id: 22,
        aimCount: 5,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [
          AimOption.One,
          AimOption.Two,
          AimOption.Three,
          AimOption.Four,
          AimOption.Five
        ],
      ),
      Mission(
        id: 23,
        aimCount: 6,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 24,
        aimCount: 6,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.First, AimOption.Second, AimOption.Comms],
      ),
      Mission(
        id: 25,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 26,
        aimCount: 3,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Hidden],
      ),
      Mission(
        id: 27,
        aimCount: 6,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Last, AimOption.Comms],
      ),
      Mission(
        id: 28,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Comms],
      ),
      Mission(
        id: 29,
        aimCount: 6,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [
          AimOption.First,
          AimOption.Second,
          AimOption.Third,
          AimOption.Comms
        ],
      ),
      Mission(
        id: 30,
        aimCount: 6,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Two, AimOption.Three],
      ),
      Mission(
        id: 31,
        aimCount: 7,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 32,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 33,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 34,
        aimCount: 7,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.First, AimOption.Second, AimOption.Third],
      ),
      Mission(
        id: 35,
        aimCount: 7,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Two],
      ),
      Mission(
        id: 36,
        aimCount: 4,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Hidden],
      ),
      Mission(
        id: 37,
        aimCount: 8,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Comms],
      ),
      Mission(
        id: 38,
        aimCount: 8,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [
          AimOption.First,
          AimOption.Second,
          AimOption.Third,
          AimOption.Comms
        ],
      ),
      Mission(
        id: 39,
        aimCount: 8,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.One, AimOption.Two, AimOption.Three],
      ),
      Mission(
        id: 40,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 41,
        aimCount: 9,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 42,
        aimCount: 9,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 43,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 44,
        aimCount: 9,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.First, AimOption.Second, AimOption.Third],
      ),
      Mission(
        id: 45,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 46,
        aimCount: 10,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      ),
      Mission(
        id: 47,
        aimCount: 3,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.Last],
      ),
      Mission(
        id: 48,
        aimCount: 10,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [AimOption.First, AimOption.Second, AimOption.Third],
      ),
      Mission(
        id: 49,
        aimCount: 0,
        attempts: 0,
        satelliteUsed: false,
        aimOptions: [],
      )
    ];
  }
}
