import 'package:the_crew_companion/entities/aimOption.dart';

import 'entities/mission.dart';

class Story {
  static final List<Mission> missions = [
    Mission(0, "Mission 1", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum", 1, 0, false, [AimOption.One, AimOption.First, AimOption.Second, AimOption.Last]),
    Mission(1, "Mission 2", "Description 2", 2, 0, false, [AimOption.One]),
    Mission(2, "Mission 3", "Description 3", 3, 0, false, [AimOption.One, AimOption.Two]),
    Mission(3, "Mission 4", "Description 4", 3, 0, false, [AimOption.One, AimOption.Second, AimOption.Last]),
    Mission(4, "Mission 5", "Description 5", 4, 0, false, []),
    Mission(5, "Mission 6", "Description 6", 3, 0, false, [AimOption.One, AimOption.First, AimOption.Second, AimOption.Last]),
    Mission(6, "Mission 7", "Description 7", 5, 0, false, []),
    Mission(7, "Mission 8", "Description 8", 0, 0, false, []),
    Mission(8, "Mission 9", "Description 9", 0, 0, false, []),
    Mission(9, "Mission 10", "Description 10", 0, 0, false, []),
    Mission(10, "Mission 11", "Description 11", 0, 0, false, []),
    Mission(11, "Mission 12", "Description 12", 0, 0, false, []),
    Mission(12, "Mission 13", "Description 13", 0, 0, false, []),
    Mission(13, "Mission 14", "Description 14", 0, 0, false, []),
    Mission(14, "Mission 15", "Description 15", 0, 0, false, []),
    Mission(15, "Mission 16", "Description 16", 0, 0, false, []),
    Mission(16, "Mission 17", "Description 17", 0, 0, false, []),
    Mission(17, "Mission 18", "Description 18", 0, 0, false, []),
    Mission(18, "Mission 19", "Description 19", 0, 0, false, []),
    Mission(19, "Mission 20", "Description 20", 0, 0, false, []),
    Mission(20, "Mission 21", "Description 21", 0, 0, false, []),
    Mission(21, "Mission 22", "Description 22", 0, 0, false, []),
    Mission(22, "Mission 23", "Description 23", 0, 0, false, []),
    Mission(23, "Mission 24", "Description 24", 0, 0, false, []),
    Mission(24, "Mission 25", "Description 25", 0, 0, false, []),
    Mission(25, "Mission 26", "Description 26", 0, 0, false, []),
    Mission(26, "Mission 27", "Description 27", 0, 0, false, []),
    Mission(27, "Mission 28", "Description 28", 0, 0, false, []),
    Mission(28, "Mission 29", "Description 29", 0, 0, false, []),
    Mission(29, "Mission 30", "Description 30", 0, 0, false, []),
    Mission(30, "Mission 31", "Description 31", 0, 0, false, []),
    Mission(31, "Mission 32", "Description 32", 0, 0, false, []),
    Mission(32, "Mission 33", "Description 33", 0, 0, false, []),
    Mission(33, "Mission 34", "Description 34", 0, 0, false, []),
    Mission(34, "Mission 35", "Description 35", 0, 0, false, []),
    Mission(35, "Mission 36", "Description 36", 0, 0, false, []),
    Mission(36, "Mission 37", "Description 37", 0, 0, false, []),
    Mission(37, "Mission 38", "Description 38", 0, 0, false, []),
    Mission(38, "Mission 39", "Description 39", 0, 0, false, []),
    Mission(39, "Mission 40", "Description 40", 0, 0, false, []),
    Mission(40, "Mission 41", "Description 41", 0, 0, false, []),
    Mission(41, "Mission 42", "Description 42", 0, 0, false, []),
    Mission(42, "Mission 43", "Description 43", 0, 0, false, []),
    Mission(43, "Mission 44", "Description 44", 0, 0, false, []),
    Mission(44, "Mission 45", "Description 45", 0, 0, false, []),
    Mission(45, "Mission 46", "Description 46", 0, 0, false, []),
    Mission(46, "Mission 47", "Description 47", 0, 0, false, []),
    Mission(47, "Mission 48", "Description 48", 0, 0, false, []),
    Mission(48, "Mission 49", "Description 49", 0, 0, false, []),
    Mission(49, "Mission 50", "Description 50", 0, 0, false, [])
  ];
}