name: CD

on:
  push:
    tags:
      - "*.*.*" # on every version tag will build a new android artifact.
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute infos
        id: release
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "::set-output name=tag::${TAG}"
          echo "::set-output name=buildNumber::${TAG//.}"
          echo "::set-output name=releaseName::v${TAG}-Beta"

      - name: Release infos
        run: |
          echo ${{ steps.release.outputs.tag }}
          echo ${{ steps.release.outputs.buildNumber }}
          echo ${{ steps.release.outputs.releaseName }}

      - name: Compute Changelog
        uses: ScottBrenner/generate-changelog-action@v1.3.3
        id: Changelog

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install dependencies
        run: dart pub get

      - name: Unit tests
        run: flutter test -r expanded

      - name: Build Web
        run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.JOSHUAARUS_GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_CREW_COMPANION }}"
          projectId: the-crew-companion

      - name: Build APK
        run: flutter build apk --build-name ${{ steps.release.outputs.tag }} --build-number ${{ steps.release.outputs.buildNumber }} --split-per-abi --release

      # - name: Build APPBUNDLE
      #   run: flutter build appbundle --release

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.JOSHUAARUS_GITHUB_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          name: ${{ steps.release.outputs.releaseName }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
