# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on: [push]
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: dart pub get
      
      - name: Build APK
        run: flutter build apk
        
      # - name: Build IOS
      #   run: flutter build ios

      - name: Build Web
        run: flutter build web

      - name: Analyze project source
        run: dart analyze