# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Last build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        uses: joshuaarus/github-actions-analyze-dart@v1.5.4
        with:
          fail-on-warnings: true
          working-directory: "./lib"

  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: dart pub get

      - name: Unit tests
        run: flutter test -r expanded

  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build APK
        run: flutter build apk

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build IOS
        run: flutter build ios --release --no-codesign

  build_web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build Web
        run: flutter build web

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: dart pub get

      - name: Config
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build web
